export const ROUTES_NAME = {
  LOG_IN: "/",
  PRODUCT_LIST: "/",
  VIEW_PRODUCT: "/:id",
  ABOUTE_US: "/aboute-us",
};

export const ROUTES_DEFINATION = {
  LOG_IN: ROUTES_NAME.LOG_IN,
  PRODUCT_LIST: ROUTES_NAME.PRODUCT_LIST,
  VIEW_PRODUCT:ROUTES_NAME.VIEW_PRODUCT,
  ABOUTE_US: ROUTES_NAME.ABOUTE_US,
};
