export const ROUTES_NAME = {
  LOG_IN: "/",
  PRODUCT_LIST: "/",
  VIEW_PRODUCT: "/:id",
  USER_LIST: "/user",
  CREATE_USER_PAGE: "/user/create-user",
  UPDATE_USER: "/user/create-user/:id",
  ABOUTE_US: "/aboute-us",
};

export const ROUTES_DEFINATION = {
  LOG_IN: ROUTES_NAME.LOG_IN,
  PRODUCT_LIST: ROUTES_NAME.PRODUCT_LIST,
  VIEW_PRODUCT: ROUTES_NAME.VIEW_PRODUCT,
  USER_LIST: ROUTES_NAME.USER_LIST,
  CREATE_USER_PAGE: ROUTES_NAME.CREATE_USER_PAGE,
  UPDATE_USER: ROUTES_NAME.UPDATE_USER,
  ABOUTE_US: ROUTES_NAME.ABOUTE_US,
};
